name: Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: tusgino/llm-code-reviewer@v1
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          
          GEMINI_MODEL: 'gemini-1.5-flash-002'          
          INPUT_EXCLUDE: '*.md,*.txt'          
          HUMAN_LANGUAGE: 'en'
          PRIMARY_MODEL: 'gemini'